add new feature: analyze abstract class, abstract method and static method
xjtu-enre/ENRE-py pull request #1
Opened 2022-07-01 14:04 UTC by Hydrion-Qlz

there are many ways to recognize a **abstract class**:
- inherit from ABC(abstract base class)
- inner method is decorated by `@abstractmethod` decorator
- inner method raise NotImplementError

for third one, here's the example:
```python
class A_abstract(object):
    def __init__(self):
        if self.__class__.__name__ == "A_abstract": 
            raise NotImplementedError("You can't instantiate this abstract class. Derive it, please.")
```

besides, for analyzing **abstract method and static method**, i just using the decorator (`@abstractmethod` or `@staticmethod`)to judge them

as an example, for input
```python
class A_abstract(object):
    def __init__(self):
        # quite simple, old-school way.
        if self.__class__.__name__ == "A_abstract": 
            raise NotImplementedError("You can't instantiate this abstract class. Derive it, please.")
    
    @abstractmethod
    def test(self):
        pass

class B(A_abstract):
    @staticmethod
    def __init__(self):
        pass
    
    @staticmethod
    def test_raise(self):
        pass
    
    def test_decorator(self):
        pass
```
it output as follow:
```python
analyze result
-----------------------------
class name: A_abstract
is_abstract: True
abstract_method: ['test']
static_method: []
-----------------------------
class name: B
is_abstract: False
abstract_method: []
static_method: ['__init__', 'test_raise']
```

2022-07-03 07:45 UTC, Butter934 requested changes

2022-07-03 07:45 UTC, Butter934 commented on enre/analysis/analyze_abstract.py
> +from _ast import ClassDef, FunctionDef, Raise, Name, Call
尽量不要从, _ast引入, 这些类ast模块里都有

2022-07-03 07:45 UTC, Butter934 commented on enre/analysis/analyze_abstract.py
> +    def visit_ClassDef(self, node: ClassDef) -> Any:
没有返回值或返回None, 返回类型应该是None, 只有无法确定返回什么的时候才返回Any

2022-07-03 07:45 UTC, Butter934 commented on enre/analysis/analyze_abstract.py
> +        self.result[self.current_class] = dict(
通过名字存储类的信息不太严谨, 在你的实现中, 如果内部又定义了一个同名类(虽然几乎不可能发生), 就会覆盖掉外部类的信息. 还有我个人觉得最好还是用一个结构化的数据存储这些信息, 而不是用dict, 这样有利于类型检查, 虽然在这里影响不大

2022-07-03 07:45 UTC, Butter934 commented on enre/analysis/analyze_abstract.py
> +        # node.exc: Call
判断raise是否是NotImplemented是没有错的. 但是不应该一个类的body中只是存在raise NotImplemented就判断为抽象类, 一种反例的情况: 
```py
class Out:
    class AbstractInner:
        def abstract_method(self):
              raise NotImplementedError("")
```
我觉得这种情况Out不应该被判断成抽象类

2022-07-03 07:54 UTC, Hydrion-Qlz commented on enre/analysis/analyze_abstract.py
> +        # node.exc: Call
在这种情况下是不是应该AbstractInner应该是抽象类，但是Out不是抽象类

2022-07-03 07:57 UTC, Butter934 commented on enre/analysis/analyze_abstract.py
> +        # node.exc: Call
我觉得是的, 因为它没有成员方法是抽象的

2022-07-03 08:03 UTC, Butter934 commented on enre/analysis/analyze_abstract.py
> +        # node.exc: Call
我觉得判断规则是这样的, 对于方法: 
如果方法体只由raise NotImplemented组成, 则这是一个抽象方法; 
对于一个类:
如果其包括抽象方法或者__init__或__new__符合之前讨论的那两种形式, 则判定为抽象类

2022-07-10 01:58 UTC, Hydrion-Qlz commented
`Commits on Jul 10, 2022` 添加了对于内部抽象类的分析，修改了上面提到的多数问题

现在遗留一个问题是无法实现对于`__init__`和`__new__`中if条件的分析

现在完成的功能对于输入：
```python
class A_abstract(object):
    class inner:
        def __init__(self):
            if self.__class__.__name__ == "inner": 
                raise NotImplementedError("You can't instantiate this abstract class. Derive it, please.")
        
        def __new__(self):
            if self.__class__.__name__ == "inner": 
                raise NotImplementedError("You can't instantiate this abstract class. Derive it, please.")
        
        def bb(self):
            if self.__class__.__name__ == "inner": 
                raise NotImplementedError("You can't instantiate this abstract class. Derive it, please.")
        
        @abstractmethod
        def test(self):
            pass
            
class B(A_abstract):
    @staticmethod
    def __init__(self):
        pass
    
    @staticmethod
    def test_raise(self):
        pass
    
    def test_decorator(self):
        pass
```

输出：

```python
analyze result
-----------------------------
name : A_abstract
is_abstract : False
abstract_method : []
static_method : []
-----------------------------
name : A_abstract.inner
is_abstract : True
abstract_method : ['__init__', '__new__', 'test']
static_method : []
-----------------------------
name : B
is_abstract : False
abstract_method : []
static_method : ['__init__', 'test_raise']
```

2022-07-12 05:19 UTC, merged